## Load and Import

In [38]:
import pandas as pd
import numpy as np

In [39]:
train_set = pd.read_csv("../data/training_set_VU_DM.csv", nrows = 500000)

In [40]:
train_set.head()

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,893,3,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,10404,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
2,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,21315,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
3,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,27348,2,4.0,...,NaN,NaN,NaN,NaN,-1.0,0.0,5.0,0,NaN,0
4,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,29604,4,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0

# Part 2 - Eda

In [41]:
df = train_set.copy()

In [42]:
print(df.shape)
df.duplicated(subset = ["srch_id", "prop_id"]).sum()  # prop_id is always unique within one search

(500000, 54)

np.int64(0)

In [43]:
df.dtypes

srch_id                          int64
date_time                       object
site_id                          int64
visitor_location_country_id      int64
visitor_hist_starrating        float64
visitor_hist_adr_usd           float64
prop_country_id                  int64
prop_id                          int64
prop_starrating                  int64
prop_review_score              float64
prop_brand_bool                  int64
prop_location_score1           float64
prop_location_score2           float64
prop_log_historical_price      float64
position                         int64
price_usd                      float64
promotion_flag                   int64
srch_destination_id              int64
srch_length_of_stay              int64
srch_booking_window              int64
srch_adults_count                int64
srch_children_count              int64
srch_room_count                  int64
srch_saturday_night_bool         int64
srch_query_affinity_score      float64
orig_destination_distance      float64
random_bool                      int64
comp1_rate                     float64
comp1_inv                      float64
comp1_rate_percent_diff        float64
comp2_rate                     float64
comp2_inv                      float64
comp2_rate_percent_diff        float64
comp3_rate                     float64
comp3_inv                      float64
comp3_rate_percent_diff        float64
comp4_rate                     float64
comp4_inv                      float64
comp4_rate_percent_diff        float64
comp5_rate                     float64
comp5_inv                      float64
comp5_rate_percent_diff        float64
comp6_rate                     float64
comp6_inv                      float64
comp6_rate_percent_diff        float64
comp7_rate                     float64
comp7_inv                      float64
comp7_rate_percent_diff        float64
comp8_rate                     float64
comp8_inv                      float64
comp8_rate_percent_diff        float64
click_bool                       int64
gross_bookings_usd             float64
booking_bool                     int64
dtype: object

In [44]:
df.columns

Index(['srch_id', 'date_time', 'site_id', 'visitor_location_country_id',
       'visitor_hist_starrating', 'visitor_hist_adr_usd', 'prop_country_id',
       'prop_id', 'prop_starrating', 'prop_review_score', 'prop_brand_bool',
       'prop_location_score1', 'prop_location_score2',
       'prop_log_historical_price', 'position', 'price_usd', 'promotion_flag',
       'srch_destination_id', 'srch_length_of_stay', 'srch_booking_window',
       'srch_adults_count', 'srch_children_count', 'srch_room_count',
       'srch_saturday_night_bool', 'srch_query_affinity_score',
       'orig_destination_distance', 'random_bool', 'comp1_rate', 'comp1_inv',
       'comp1_rate_percent_diff', 'comp2_rate', 'comp2_inv',
       'comp2_rate_percent_diff', 'comp3_rate', 'comp3_inv',
       'comp3_rate_percent_diff', 'comp4_rate', 'comp4_inv',
       'comp4_rate_percent_diff', 'comp5_rate', 'comp5_inv',
       'comp5_rate_percent_diff', 'comp6_rate', 'comp6_inv',
       'comp6_rate_percent_diff', 'comp7_rate', 'comp7_inv',
       'comp7_rate_percent_diff', 'comp8_rate', 'comp8_inv',
       'comp8_rate_percent_diff', 'click_bool', 'gross_bookings_usd',
       'booking_bool'],
      dtype='object')

### Handling Time

In [46]:
df["date_time"] = pd.to_datetime(df["date_time"])
date_col = df["date_time"].dt.floor("D")
df.insert(2, "date", date_col)
df.head()

,srch_id,date_time,date,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,1,2013-04-04 08:32:15,2013-04-04,12,187,NaN,NaN,219,893,3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1,1,2013-04-04 08:32:15,2013-04-04,12,187,NaN,NaN,219,10404,4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
2,1,2013-04-04 08:32:15,2013-04-04,12,187,NaN,NaN,219,21315,3,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
3,1,2013-04-04 08:32:15,2013-04-04,12,187,NaN,NaN,219,27348,2,...,NaN,NaN,NaN,NaN,-1.0,0.0,5.0,0,NaN,0
4,1,2013-04-04 08:32:15,2013-04-04,12,187,NaN,NaN,219,29604,4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0

In [48]:
df.dtypes[:3]

srch_id               int64
date_time    datetime64[ns]
date         datetime64[ns]
dtype: object

### Missing Values

In [65]:
# Overall Missing Value Ratios per Features
round(df.isna().sum().sort_values(ascending = False) / df.shape[0], 2)

comp1_rate_percent_diff        0.98
comp6_rate_percent_diff        0.98
comp1_rate                     0.98
comp1_inv                      0.97
comp4_rate_percent_diff        0.97
gross_bookings_usd             0.97
comp7_rate_percent_diff        0.97
comp6_rate                     0.95
visitor_hist_starrating        0.95
visitor_hist_adr_usd           0.95
comp6_inv                      0.94
comp4_rate                     0.94
srch_query_affinity_score      0.93
comp7_rate                     0.93
comp4_inv                      0.93
comp7_inv                      0.93
comp3_rate_percent_diff        0.90
comp2_rate_percent_diff        0.89
comp8_rate_percent_diff        0.88
comp5_rate_percent_diff        0.83
comp3_rate                     0.69
comp3_inv                      0.67
comp8_rate                     0.62
comp8_inv                      0.60
comp2_rate                     0.59
comp2_inv                      0.57
comp5_rate                     0.55
comp5_inv                      0.52
orig_destination_distance      0.32
prop_location_score2           0.22
prop_review_score              0.00
srch_children_count            0.00
srch_adults_count              0.00
srch_booking_window            0.00
prop_starrating                0.00
prop_country_id                0.00
prop_id                        0.00
visitor_location_country_id    0.00
site_id                        0.00
srch_id                        0.00
date                           0.00
date_time                      0.00
srch_length_of_stay            0.00
srch_destination_id            0.00
promotion_flag                 0.00
price_usd                      0.00
position                       0.00
prop_log_historical_price      0.00
prop_location_score1           0.00
prop_brand_bool                0.00
random_bool                    0.00
srch_room_count                0.00
srch_saturday_night_bool       0.00
click_bool                     0.00
booking_bool                   0.00
dtype: float64

In [ ]:
df.groupby("srch_id").agg({})

In [64]:
# Zero Values for 0 data

### Basic Stats

In [47]:
df.nunique()

### Group By Search ID Stats

In [70]:
# Booking Ratio
booking_ratio = (df.groupby("srch_id")["booking_bool"].mean()  != 0).mean()
print(f"Ratio of booking in a search: {booking_ratio:.2f}")

Ratio of booking in a search: 0.69

In [76]:
# At least one click Ratio per Search
click_ratio = (df.groupby("srch_id")["click_bool"].sum() != 0).mean()
average_n_clicks = (df.groupby("srch_id")["click_bool"].sum()).mean()
print(f"Ratio of clicking at least one time in a search: {click_ratio:.2f}")
print(f"Average number of clicks per search: {average_n_clicks:.2f}")

Ratio of clicking at least one time in a search: 1.00
Average number of clicks per search: 1.12